add LightsaberTimerView
kacus/CC-StarWarsQuiz pull request #11
Opened 2021-01-03 17:32 UTC by pkol92

2021-01-03 18:42 UTC, kacus requested changes

2021-01-03 18:42 UTC, kacus commented on src/js/app/views/lightsaberTimerView.js
> +        this.parent = this.getElement(parent)
parent is already selected DOM element so 
> this.parent = parent

should be enough.

2021-01-03 18:42 UTC, kacus commented on src/js/app/views/lightsaberTimerView.js
> +    }
What is it for? You have never used this method.

2021-01-03 18:42 UTC, kacus commented on src/js/app/views/lightsaberTimerView.js
> +        this.parent.append(this.timerView)
I think this part should be contained in .display(leftTime, maxTime) method.
We don't want to display it when view is created, but when controller ask for it by calling .display() method

2021-01-03 18:42 UTC, kacus commented on src/js/app/views/lightsaberTimerView.js
> +        this.pathLightsaber.style.width = `(${timeLeft}*100/${maxTime})%`
You are using div to represent progress. There in HTML5 is more elegant way to do that.
Just use <progress> tag. More about it here:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress

2021-01-04 17:02 UTC, kacus requested changes

2021-01-04 17:02 UTC, kacus commented on src/js/app/views/lightsaberTimerView.js
> +        this.progress = this.createElement('progress')
You add 'progress' bar as i asked you, but you forgot to set 'value' and 'max' attributes, so it doesn't work.

2021-01-04 17:02 UTC, kacus commented on src/js/app/views/lightsaberTimerView.js
> +        this.lightsaber.append(this.pathLightsaber)
What is it for?

2021-01-06 01:19 UTC, pkol92 commented on src/js/app/views/lightsaberTimerView.js
> +class LightsaberTimerView {
Added export default at the end of file

2021-01-06 01:20 UTC, pkol92 commented on src/js/app/views/lightsaberTimerView.js
> +        if(className) element.className.add(className)
Done, changed to `classList`

2021-01-06 01:21 UTC, pkol92 commented on src/js/app/views/lightsaberTimerView.js
> +        this.progress = this.createElement('progress')
Done

2021-01-06 01:21 UTC, pkol92 commented on src/js/app/views/lightsaberTimerView.js
> +        this.lightsaber.append(this.pathLightsaber)
Ok, I deleted it

2021-01-06 19:51 UTC, kacus approved these changes

2021-01-06 19:51 UTC, kacus commented on src/js/app/views/lightsaberTimerView.js
> +        this.lightsaber = this.createElement('div','lightsaber');
Now you can add in this place img of lightsaber. I leave you decision about where the image should be placed, inside of div.lightsaber or instead of this div.

2021-01-06 19:52 UTC, merged