Feature/type menu view
kacus/CC-StarWarsQuiz pull request #17
Opened 2021-01-09 12:35 UTC by s-sliwinski

Reaview MenuView

2021-01-09 15:48 UTC, kacus requested changes

2021-01-09 15:48 UTC, kacus commented on src/js/app/views/typeMenuView.js
> +        this.parent.innerHTML = "";
If you pack whole menu in one separated div you shouldn't reset parent, because there may be another view.
So you have two options:
- parent is container and i append buttons inside.
- parent is root to which you append new created container.

2021-01-09 15:48 UTC, kacus commented on src/js/app/views/typeMenuView.js
> +// }
Remember to delete old code like this.
It's not good practice.

2021-01-10 13:19 UTC, kacus requested changes

2021-01-10 13:19 UTC, kacus commented on src/js/app/views/typeMenuView.js
> +        const menuContainer = this.createElement('div', 'menu__container');
This class name doesn't follow BEM, 'menu' is block so you can name it just 'menu' there is no need to add '__container' because it isn't element.

2021-01-10 13:19 UTC, kacus commented on src/js/app/views/typeMenuView.js
> +            const menuBtn = this.createElement('button', 'menu__button');
I think 'menu__option' is more accurate name. What do you think?

2021-01-10 15:22 UTC, s-sliwinski commented on src/js/app/views/typeMenuView.js
> +            const menuBtn = this.createElement('button', 'menu__button');
Imo it's styling button so i think 'menu__button' is more descriptive ok.

2021-01-10 19:57 UTC, kacus approved these changes

2021-01-10 19:57 UTC, merged