displaying question with possible answers in random order
kacus/CC-StarWarsQuiz pull request #8
Opened 2020-12-31 08:10 UTC by Kinetic639

Im not 100% sure if thats the best way to display possible answers in random order...

2020-12-31 11:30 UTC, kacus requested changes

2020-12-31 11:30 UTC, kacus commented on src/js/app/views/questionView.js
> +    display(answers) {
You didn't bind answerHandler to answers. Each answer should have event with corresponding answerHandler call.
For example button with answers with id 5 should call answerHandler(5) when user click on it.

Just add method bindAnswersHandler() and bind handler in it, then call this method in display.

2020-12-31 11:30 UTC, kacus commented on src/js/app/views/questionView.js
> +        questionWrapper.appendChild(currentQuestionImage)
Image should be outside wrapper to meet html structure we decide to have.
![image](https://user-images.githubusercontent.com/54528490/103408466-e1141500-4b62-11eb-97ee-c3a1c7cbfe00.png)

2020-12-31 11:30 UTC, kacus commented on src/styles/App.css
> +box-shadow: 4px 5px 4px rgba(0, 0, 0, 0.5) inset;
Remember to use some code formater to keep code easy to read.

2020-12-31 15:04 UTC, Kinetic639 commented on src/styles/App.css
> +}
removed unwanted css in https://github.com/kacus/CC-StarWarsQuiz/pull/8/commits/1c54b0e2d38dce220f883bc0051e0b86d71c7281

2020-12-31 15:19 UTC, Kinetic639 commented on src/styles/App.css
> +box-shadow: 4px 5px 4px rgba(0, 0, 0, 0.5) inset;
i have formater, possibly commited code before saving file so the formatter didn't run. Now this problem is fixed as all this code has beed removed in https://github.com/kacus/CC-StarWarsQuiz/pull/8/commits/1c54b0e2d38dce220f883bc0051e0b86d71c7281

2020-12-31 15:44 UTC, Kinetic639 commented on src/js/app/views/questionView.js
> +        questionWrapper.appendChild(currentQuestionImage)
i have made it a little different because i was considering how the layout will look with added header.
thats why i wrapped whole question in separate wrapper marked on the screen as the red one. Won't that be better?
![image](https://user-images.githubusercontent.com/29673448/103416491-5396ec00-4b87-11eb-99e2-d135fc77c415.png)

2020-12-31 15:45 UTC, Kinetic639 commented on src/js/app/views/questionView.js
> +        questionWrapper.appendChild(currentQuestionImage)
Also forgot that on the bottom there will be the lightsaber timer aswell...

2020-12-31 16:03 UTC, kacus commented on src/js/app/views/questionView.js
> +        questionWrapper.appendChild(currentQuestionImage)
It's exactly how it will look. But your code makes structure like this:
![image](https://user-images.githubusercontent.com/54528490/103417067-817d3000-4b89-11eb-82a6-98f23d427ac5.png)
We display QuestionView in currently existing wrapper so we don't need to make another one, but inside this parent we still want to have question text and answers in separate wrapper for easier styling.
`this.parent.appendChild(currentQuestionImage)` should make a thing.

2021-01-01 09:51 UTC, Kinetic639 commented on src/js/app/views/questionView.js
> +        questionWrapper.appendChild(currentQuestionImage)
removed unwanted wrapper in https://github.com/kacus/CC-StarWarsQuiz/pull/8/commits/96feac8bd2f4b224bad1eadaf1d18286c4c1e8e6

2021-01-02 21:06 UTC, Kinetic639 commented on src/js/app/views/questionView.js
> +    display(answers) {
solved in https://github.com/kacus/CC-StarWarsQuiz/pull/8/commits/3caeef000ad5fa6268e24aa732b1a53a0ebda162

2021-01-02 21:11 UTC, kacus approved these changes

2021-01-02 21:12 UTC, merged